/**
 * Icon re-exports from lucide-react.
 * All existing import names are preserved for backward compatibility.
 * Every icon is a standard lucide-react component accepting className, size, strokeWidth, etc.
 */

export {
  Plane as IconPlane,
  Search as IconSearch,
  Calendar as IconCalendar,
  User as IconUser,
  Users as IconUsers,
  Mail as IconMail,
  LogOut as IconLogout,
  ArrowRight as IconArrowRight,
  ArrowUpDown as IconSwap,
  Clock as IconClock,
  Check as IconCheck,
  X as IconX,
  Menu as IconMenu,
  ChevronDown as IconChevronDown,
  ExternalLink as IconExternalLink,
  Loader2 as IconLoader,
  MapPin as IconMapPin,
  Plus as IconPlus,
  Sparkles as IconSparkles,
  Send as IconSend,
  Bot as IconBot,
  ArrowLeftRight as IconSwapHorizontal,
  Minus as IconMinus,
  Radar as IconRadar,
  Route as IconRoute,
  Headset as IconHeadset,
  LayoutGrid as IconGrid,
  ChevronUp as IconChevronUp,
  Signal as IconSignal,
  Share2 as IconShare,
  Bell as IconBell,
  Copy as IconCopy,
  // Additional icons for the redesign
  PlaneTakeoff as IconPlaneTakeoff,
  PlaneLanding as IconPlaneLanding,
  Shield as IconShield,
  Eye as IconEye,
  Settings as IconSettings,
  Home as IconHome,
  Bookmark as IconBookmark,
  AlertTriangle as IconAlertTriangle,
  Info as IconInfo,
  ChevronRight as IconChevronRight,
  ChevronLeft as IconChevronLeft,
  Filter as IconFilter,
  SortAsc as IconSortAsc,
  Globe as IconGlobe,
  Wifi as IconWifi,
  Zap as IconZap,
  TrendingUp as IconTrendingUp,
  BarChart3 as IconBarChart,
  RefreshCw as IconRefresh,
  Download as IconDownload,
  MessageCircle as IconMessageCircle,
  Phone as IconPhone,
  Briefcase as IconBriefcase,
  MapPinned as IconMapPinned,
  Timer as IconTimer,
  CircleCheck as IconCircleCheck,
  CircleAlert as IconCircleAlert,
  CircleX as IconCircleX,
  Luggage as IconLuggage,
  Star as IconStar,
} from 'lucide-react';
